#Number Guessing
def checknum(x):
    print
    y=int(input("Enter your guess : "))
    if x==y:
        return True
    else:
        return False

import random
x=random.randint(10,100)
score=100
chance=5
count=0
print("\nA Random number has been generated by system in range 10 to 100")
print("\nYou have 5 chances to guess the correct answer.")
while True:
    if checknum(x):
        print("\n\tHurray!Correct Guess.\n\tScore = ",score)
        break
    else:
        count=count+1
        chance-=1
        print("Ohoh....Wrong answer.")
        print("You have",chance,"chances left.")
        score-=20
        if count==4:
            for i in range(3,11):
                if(x%i==0):
                    print("\nHint 4 : The number is divisible by",i)
                    break
        elif count==1:
            if(x>50):
                print("\nHint 1 : The number is greater than 50")
            else:
                print("\nHint 1 : The number is lesser than or equal to 50")
        elif count==3:
            s=list(str(x))
            s=[int(i) for i in s]
            print("\nHint 3 : The sum of the digits of the number is",sum(s))
        elif count==2:
            prime=0
            for j in range(2,101):
                if x%j==0:
                    prime+=1
            if prime==1:
                print("\nHint 2 : The number is prime")
            else:
                print("\nHint 2 : The number is not prime")
        elif count==5:
            print("Sorry your turns are over.\nYour Score is 0")
            print("The correct answer is:",x)
            exit(1)
        continue
